routes/admin.php
<?php
use App\Message;
// delete news file


Route::get('/login', 'Auth\LoginController@showAdminLoginForm')->name('admin.login.form');
Route::get('/admin-user', function() {
    return response()->json(Auth::guard('admin')->user(), 200);
});
Route::get('/register', 'Auth\RegisterController@showAdminRegisterForm')->name('admin.register');
Route::get('/logout', 'Auth\LoginController@adminLogout')->name('admin.logout');

Route::post('/login', 'Auth\LoginController@adminLogin')->name('admin.login');
Route::post('/register', 'Auth\RegisterController@createAdmin');

Route::group(['middleware' => 'auth:admin', 'namespace' => 'Admin'], function () {
    Route::post('/delete-news-file', 'NewsController@deleteFile');

    Route::get('/welcome-admin', 'WelcomeController@index');
    Route::resource('/news', 'NewsController');
    Route::get('/order/list', 'OrderController@index');
    Route::resource('/shops', 'ShopsController');
    Route::resource('/partners', 'PartnersController');
    Route::resource('/faq', 'FaqController');
    Route::resource('/countries', 'CountriesController');
    Route::resource('/roles', 'RolesController');
    Route::resource('/apis', 'ApisController');
    Route::resource('/admins', 'AdminsController');
    Route::resource('/slider', 'SliderController');
    Route::resource('/all-invoices', 'AllInvoicesController');
    Route::get('/contact', 'ContactController@index')->name('admin.contact.index');

    Route::resource('/invoices', 'InvoiceController');
    Route::get('/invoices/get/xml', 'InvoiceController@xml');
//    Route::get('/invoices/status', 'InvoiceController@getDataStatus');
    Route::get('/invoices/get/test', 'InvoiceController@test');
    Route::get('/invoices/get/test111', 'InvoiceController@test111');
    Route::get('/invoices/change-purchase/{purchase_no}', 'InvoiceController@changePurchase');
    Route::get('/invoices/get/manifest', 'InvoiceController@manifest');
    Route::get('/invoices/get/manifest2', 'InvoiceController@manifest2');
    Route::post('/invoices/check-storage', 'InvoiceController@addToOnTheWay');
    Route::post('/invoices/check-waiting', 'InvoiceController@addToForeignStorage');
    Route::post('/invoices/check-road', 'InvoiceController@addToStorage');
    Route::post('/invoices/check-native-storage', 'InvoiceController@addToCompleted');
    Route::post('/invoices/change-status', 'InvoiceController@changeStatus');
    Route::post('/invoices/change-all-stauses', 'InvoiceController@changeAllStatuses');
    Route::post('/invoices/send-invoiceless-message', 'InvoiceController@sendInvoicelessMessage');
    Route::get('/invoices/waybill/{id}', 'InvoiceController@waybill');
    Route::resource('/sack', 'SackController');
    Route::get('/sack/get/test', 'SackController@test');
    Route::post('/sack/addInvoice', 'SackController@addInvoice');
    Route::get('/sack/invoices/{id}', 'SackController@invoices');
    Route::resource('/dispatch', 'DispatchController');
    Route::post('/dispatch/addSack', 'DispatchController@addSack');

    Route::get('/invoiceless', 'InvoicelessController@index')->name('invoiceless.index');
    Route::post('/invoiceless', 'InvoicelessController@store')->name('invoiceless.store');
    Route::post('/invoiceless/send/{id}', 'InvoicelessController@send')->name('invoiceless.send');
    Route::get('/invoiceless/done/{id}', 'InvoicelessController@done')->name('invoiceless.done');

    Route::get('/get-admin-data', 'AdminsController@getAdminId')->name('getAdminData');
    Route::get('/accountants', 'AdminsController@getAccountants')->name('getAccountants');
    Route::post('/rejection', 'ProductsController@rejection')->name('rejection');
    Route::post('/refusal', 'RelUserProductsController@refusal')->name('refusal');
    Route::post('/changeExtrasLink', 'ProductsController@changeExtrasLink')->name('changeExtrasLink');  // new

    Route::post('/order/invoice-upload', 'ProductsController@invoiceUpload')->name('invoiceUpload');
    Route::post('/order/invoice-upload_new', 'ProductsController@invoiceUpload_new')->name('invoiceUpload_new');
    Route::post('/order/invoice-upload/change', 'ProductsController@updateInvoice')->name('invoiceChangeFile');
    Route::post('/order/finish', 'AdminsAcceptedProductsController@finishOrder')->name('finishOrder');
    Route::post('/order/ordered', 'RelUserProductsController@ordered')->name('ordered');
    Route::post('/order/send/invoiceData', 'InvoiceController@setInvoiceDataByBuyer')->name('sendInvoiceData');
    Route::post('/order/update/invoiceData', 'InvoiceController@updateInvoiceDataByBuyer')->name('updateInvoiceData');

    Route::get('/my-orders/list', 'RelUserProductsController@myOrders')->name('myOrders');
    Route::get('/orders/list', 'RelUserProductsController@orders')->name('orders');
    Route::get('/will-upload-invoices/list', 'RelUserProductsController@willUploadInvoices')->name('willUploadInvoices');
    Route::post('/calc-additional-price', 'RelUserProductsController@calcAddPrice')->name('calcAddPrice');


    Route::get('/orders/log', 'AdminsAcceptedProductsController@getFinishedOrdersLog')->name('ordersLog');
    Route::get('/orders', 'AdminsAcceptedProductsController@getOrders')->name('orders');
    Route::get('/orders/detail/{id}', 'AdminsAcceptedProductsController@getOrderDetail')->name('orderDetail');
    Route::get('/orders/detail/by-admin/{id}', 'AdminsAcceptedProductsController@getOrderDetailByAdmin')->name('orderDetail');
    Route::get('/orders/detail/by-user/{id}', 'AdminsAcceptedProductsController@getOrderDetailByUser')->name('orderDetailByUser'); // new
    Route::get('/will-upload-invoice/detail/by-admin/{id}', 'AdminsAcceptedProductsController@getWillUploadInvoiceDetailByAdmin')->name('willUploadInvoiceDetail');
    Route::get('/orders/detail/log/by-admin/{id}', 'AdminsAcceptedProductsController@getOrderLogDetailByAdmin')->name('orderLogDetail');
    Route::get('/accept', 'AdminsAcceptedProductsController@index')->name('accept');
    Route::post('/accept-order', 'AdminsAcceptedProductsController@acceptOrder')->name('acceptOrder');
    Route::post('/addBalance', 'UsersController@addBalance')->name('addBalance');
    Route::post('/accept/order/{id}', 'AdminsAcceptedProductsController@order')->name('order');

    Route::get('/courier', 'CourierController@index')->name('courier');

    Route::get('/courier/orders-answer-waiting', 'CourierController@getCourierAnswerOrders')->name('getCourierAnswerOrders');
    Route::get('/courier/orders-waiting', 'CourierController@getCourierOrders')->name('getCourierOrders');
    Route::get('/courier/reject-order', 'CourierController@rejectOrder');
    Route::get('/courier/check-depot', 'CourierController@checkDepot');
    Route::get('/courier/orders-delivered', 'CourierController@getDeliveredOrders')->name('getDeliveredOrders');
    Route::get('/courier/courier-users', 'CourierController@getCourierUsers')->name('getCourierUsers');
    Route::get('/courier/orders-delivered2', 'CourierController@courierDeliveryLogs')->name('courierDeliveryLogs');
    Route::post('/courier/selected', 'CourierController@courierSelected')->name('courierSelected');
    Route::post('/courier/complete-order', 'CourierController@completeOrder')->name('completeOrder');
    Route::post('/courier/give-to-depot', 'CourierController@giveToDepot')->name('giveToDepot');
    Route::get('/courier/orders-count', 'CourierController@ordersCount');
    Route::get('/courier/orders-complete-delivered/{id}', 'CourierController@completeDelivereOrder')->name('completeDeliveredOrder');
    Route::post('/courier/finish', 'CourierController@productDelivered')->name('productDelivered');
    Route::get('/courier/logs', 'CourierController@courierDeliveryLogs')->name('courierDeliveryLogs');
    Route::post('/courier/addCourier', 'CourierController@addCourier');
    Route::get('/courier/getCourierInvoices', 'CourierController@getCourierInvoices');

    Route::post('/problems/lost-packages', 'ProblemsController@searchLostPackages');
    Route::post('/problems/user-complains', 'ProblemsController@searchUserComplains');
    Route::get('/problems/complaint-types', 'ProblemsController@getComplaintTypes');
    Route::get('/problems/complaints', 'ProblemsController@getComplaints');
    Route::get('/problems/user-complaints', 'ProblemsController@getUserComplaints');
//    Route::post('/problems/add-complaint', 'ProblemsController@addComplaint');
    Route::get('/problems/get-complaint/{id}', 'ProblemsController@getComplaint');
    Route::post('/problems/send-message', 'ProblemsController@sendMessagetoUser');
//    Route::get('/problems/solve-complaint/{id}', 'ProblemsController@solveComplaint');
    Route::get('/problems/formal-complaints/{type}', 'ProblemsController@formalComplaints')->name('formalComplaints');

    Route::get('/user/list', 'UsersController@index')->name('users.list');
    Route::get('/user/allData/{id}', 'UsersController@allData')->name('users.allData');
    Route::get('/user/allData', 'UsersController@allData')->name('users.allData');
    Route::post('/user/sendEmail', 'UsersController@sendEmail')->name('users.sendEmail');
    Route::get('/user/sendEmailForAll', 'UsersController@sendEmailForAll')->name('users.sendEmail');
    Route::post('/user/sendSms', 'UsersController@sendSms')->name('users.sendSms');
    Route::get('/user/sendSmsForAll', 'UsersController@sendSmsForAll')->name('users.sendSms');

    Route::post('/product/comment', 'ProductsController@comment')->name('product.saveComment');
    Route::post('/product/saveRealPrice', 'ProductsController@saveRealPrice')->name('product.saveRealPrice');


    Route::get('/get-product-data-by-id/{id}', 'ProductsController@getProductDataById')->name('getProductDataById');
    Route::get('/print-hawb/{productId}', 'ProductsController@printHawb')->name('printHawb');
    Route::get('/user/list/block/{id}', 'UsersController@block')->name('users.block');

routes/web.php
<?php

Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/password/reset2', '\App\Http\Controllers\Site\FrontController@passwordResetWithPhone');

// CP Panel
Route::group(['middleware' => 'auth:admin', 'namespace' => 'Admin'], function (){
    Route::get('/cp', function () {
        return view('admin/welcomeadmin');
    });
});
// SIte papkasinin icindedirpayment-balance-success
Route::group(['namespace' => 'Site','as' => 'front.', 'middleware' => 'web'], function() {
    Route::get('/', 'FrontController@index')->name('main'); //OK
    Route::get('/countries', 'CountryController@index')->name('country'); //OK
    Route::get('/calculator', 'CalculatorController@index')->name('calculator'); //OK
    //Route::get('/premium', 'CalculatorController@premium')->name('premium'); //OK
    Route::post('/calculate', 'CalculatorController@calculate'); //OK
    Route::get('/calculate-currency', 'CalculatorController@calculateCurrency')->name('currency'); //Ok
    Route::get('/shops/country/{country}', 'ShopsController@index')->name('shop'); //OK
    Route::resource('/contact', 'ContactController'); //OK
    Route::get('/istifadeci-qaydalari', 'FrontController@userRules')->name('static.pages.userRules'); //OK
    Route::get('/suallar', 'FrontController@userQuestions')->name('static.pages.userQuestions'); //OK
    Route::get('/blog/{id}/{slug}', 'FrontController@newsIn'); //OK
    Route::get('/blog/{id}', 'FrontController@newsIn'); //OK

    Route::get('/news-and-announcements/{id}', 'FrontController@newsIn'); //lazimsiz
    Route::get('/news-and-announcements/{id}/{slug}', 'FrontController@newsIn'); //lazimsiz
    Route::get('/payment-balance-success', 'Panel\PaymentForBalanceController@getResponseOfPayment'); // Balansdan odenis
    Route::get('/success', 'FrontController@success')->name('success');
    Route::get('/password-sent', 'FrontController@passwordSent')->name('passwordSent2');
    Route::get('/anbar-tr', 'HomeController@anbar')->name('anbar');

    Route::post('/payment-callback', 'PaymentForProductController@getResponseOfPayment');// paytr    callbak post url
    Route::post('/payment-order-notify', 'OrderController@paymentNotify'); // paytr 2ci addim
    Route::get('/get-currency/{type}', 'FrontController@getCurrency');

    // payment callback
    Route::get('/payment-order-success', 'FrontController@paymentSuccess'); // Kart odenisi
    Route::get('/payment-success', 'FrontController@paymentSuccessBalance'); // Balans odenisi
    Route::get('/balancePayment', 'PaymentController@millionApi');
    Route::get('/{slug}', 'FrontController@staticPages')->name('static.pages.show');
});


Route::group(['namespace' => 'Front', 'middleware' => 'web'], function() {

});


//  Site papkasinin icindedir   /site/..
Route::group([ 'middleware' => ['web', 'auth'], 'namespace' => 'Site','prefix' => 'site','as' => 'front.'], function() { // authenticated routes
    Route::get('/invoice', 'InvoiceController@index')->name('invoice.index');
    Route::get('/productTypes', 'InvoiceController@productTypes')->name('invoice.product.types');
    Route::post('/invoice', 'InvoiceController@store')->name('invoice.store');
    Route::post('/invoice/edit', 'InvoiceController@edit')->name('invoice.edit');
/*
    Route::get('/track', 'Panel\TrackController@index');
    Route::get('/track/{type}', 'Panel\TrackController@index_new');
    Route::get('/track2/{type}', 'Panel\TrackController@index2');*/

});


// site papkasinin icinde ama site olmadan bir basa linkler
Route::group([ 'middleware' => ['web', 'auth'], 'namespace' => 'Site'], function() { // authenticated routes
    Route::post('/order/parse', 'OrderController@parse');
    Route::post('/order/link/insert', 'OrderController@store');
    Route::post('/order/link/insertBalance', 'OrderController@storeBalance');
});

// New User Panel Vue
Route::group([ 'middleware' => ['auth', 'isblocked'], 'namespace' => 'Site\Panel','prefix' => 'site'], function() { // authenticated routes
    Route::get('/user-panel', 'PanelController@index')->name('new-user-panel');
    Route::post('/user-panel', 'PanelController@index')->name('new-user-panel2');

    Route::get('/premium', 'PanelController@premium')->name('new-user-panel-premium');
    Route::post('/premium', 'PanelController@premium')->name('new-user-panel-premium');

    Route::get('/order/link/insert', 'OrderController@storeLink');


});

// New
/*Route::group([ 'middleware' => ['auth', 'isblocked'], 'namespace' => 'Site\Panel'], function() { // authenticated routes
    Route::get('/user-panel/get-user-data', 'PanelController@userData');
    Route::get('/user-panel/get-invoices/{type}', 'InvoicesController@index');
    Route::get('/user-panel/get-allInvoices-count', 'InvoicesController@allInvoicesCount');
    Route::get('/user-panel/get-invoices-count', 'InvoicesController@invoiceCount');
});*/

Route::group([ 'middleware' => ['auth', 'isblocked'], 'namespace' => 'Site\Panel'], function() { // authenticated routes
    Route::get('/panel/get-user-data', 'PanelController@userData');
    Route::get('/panel/clients', 'PanelController@getCorporateClients');
    Route::post('/panel/add-client', 'PanelController@addClient');
    Route::post('/panel/edit-client', 'PanelController@editClient');
    Route::get('/panel/get-invoices/{type}', 'InvoicesController@index');
    Route::get('/panel/get-invoice/{id}', 'InvoicesController@view');
    Route::get('/panel/get-invoices-count', 'InvoicesController@invoiceCount');
    Route::post('/panel/delete-invoice', 'InvoicesController@deleteInvoice');
    Route::get('/panel/order-status', 'InvoicesController@orderStatus');

});

//user-panel
Route::group([ 'middleware' => ['auth', 'isblocked'], 'namespace' => 'Front\Panel'], function() { // authenticated routes
    //Route::get('/user-panel', 'PanelController@index')->name('user-panel');
    Route::get('/user-panel/get-user-data', 'PanelController@userData');
    Route::get('/user-panel/get-user-data1', 'PanelController@userData1');
    Route::get('/user-panel/get-orders/{type}', 'OrderController@index');
    Route::get('/user-panel/get-orders2/{type}', 'OrderController@index2');
    Route::post('/user-panel/delete-basket/', 'OrderController@deleteBasket');
    Route::post('/user-panel/update-basket/', 'OrderController@updateBasket');
    Route::post('/user-panel/update-product/', 'OrderController@updateProduct');
    //Route::get('/user-panel/track', 'TrackController@index');
    Route::get('/user-panel/get-countries', 'InvoicesController@countries');
    Route::get('/user-panel/get-invoices/{type}', 'InvoicesController@index');
    Route::get('/user-panel/home_courier_invoices', 'InvoicesController@homeForCourier');
    Route::get('/user-panel/get-invoices2/{type}', 'InvoicesController@index2');
    Route::get('/user-panel/get-invoices-count', 'InvoicesController@invoiceCount');
    Route::get('/user-panel/get-allInvoices-count', 'InvoicesController@allInvoicesCount');
    Route::get('/user-panel/get-settings-data', 'SettingsController@index');
    Route::get('/user-panel/get-balance', 'BalanceController@index');
    Route::get('/user-panel/get-try-balance', 'BalanceController@indexTry');
    Route::post('/user-panel/post-settings-data', 'SettingsController@store');
    Route::post('/user-panel/post-settings-data-profile', 'SettingsController@storeProfile');
    Route::post('/user-panel/post-settings-data-passport', 'SettingsController@storePassport');
    Route::post('/user-panel/post-settings-data-password', 'SettingsController@storePassword');
    Route::post('/user-panel/post-courier-data', 'CourierController@store');
    Route::post('/user-panel/post-courier-data1', 'CourierController@store1');
    Route::post('/user-panel/post-transfer-data', 'CourierController@transferStore');
    Route::get('/user-panel/get-courier-data', 'CourierController@index');
    Route::get('/user-panel/get-courier-data2', 'CourierController@index2');
    Route::get('/user-panel/get-transfer-data', 'CourierController@indexTransfer');
    Route::get('/user-panel/get-complaints', 'QuestionsController@getComplaints');
    Route::get('/user-panel/get-complaints', 'QuestionsController@getComplaints');

    // Asistant
//    Route::post('/user-panel/get-questions', 'QuestionsdController@getDefaultQuestions');
//    Route::post('/user-panel/get-question', 'QuestionsdController@getDefaultQuestion');
//    Route::get('/user-panel/get-max-step', 'QuestionsdController@getMaxStepQuestions');

//    Route::post('/user-panel/get-questions', 'QuestionsddController@getDefaultQuestions');
//    Route::post('/user-panel/get-question', 'QuestionsddController@getDefaultQuestion');
//    Route::get('/user-panel/get-max-step', 'QuestionsddController@getMaxStepQuestions');

    Route::post('/user-panel/get-questions', 'QuestionsdddController@getDefaultQuestions');
    Route::post('/user-panel/get-question', 'QuestionsdddController@getDefaultQuestion');
    Route::get('/user-panel/get-max-step', 'QuestionsdddController@getMaxStepQuestions');
//    Route::post('/user-panel/get-next-step', 'QuestionsdddController@getNextStepQuestions');


//    Route::get('user-panel/get-complaints1', 'QuestionsController@getComplaints1');
    Route::get('/user-panel/get-complaint-messages/{id}', 'QuestionsController@getComplaintMessages');
    Route::post('/user-panel/add-complaint', 'QuestionsController@addComplaint');
    Route::get('/user-panel/complaint-types', 'QuestionsController@getComplaintTypes');
    Route::get('/user-panel/change-seen-status/{id}', 'QuestionsController@changeSeen');
    Route::post('/user-panel/send-message', 'QuestionsController@sendMessagetoAdmin');
    // for payment
    Route::post('/user-panel/pay', 'PanelController@pay');
    Route::post('/user-panel/pay-courier', 'PanelController@payOnlyCourier');
    Route::post('/user-panel/pay-courier1', 'PanelController@payOnlyCourier1');

resources/views/admin/admins/index.blade.php
@extends('layouts/admin')
@section('styles')
    <style>
        @media (min-width: 1200px) {
            .container {
                max-width: 100% !important;
            }
        }
        .box-body tr td {
            text-align: left;
        }
        .table tr th {
            text-align: left;
        }

    </style>
@endsection
@section('content')
    <div class="content-wrapper animatedParent animateOnce">
        <div style="width: 100%;" class="container">
            <a class="btn btn-primary" style="margin-bottom: 20px;" href="{{route('admins.create')}}">Admin əlavə et</a>
            <section class="paper-card">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title"><strong>Adminlər</strong></h3>
                                <br>
                            </div>
                            <div class="box-body no-padding">
                                <table class="table table-striped">
                                    <tbody>
                                    <tr>
                                        <th >#</th>
                                        <th>Ad</th>
                                        <th>Soyad</th>
                                        <th>Admin tipi</th>
                                        <th>Ətraflı</th>
                                    </tr>
                                    <tr class="search-container">
                                        <form action="" method="get" id="searchForm">
                                            <input name="search" value="true" type="hidden" class="submitClass widthFull form-control" type="text" />
                                            <th>
                                                <div class="input-group focused">
                                                    <input name="id" value="{{isset($params['id'])?$params['id']:''}}" class="form-control r-0" type="text" placeholder="id">
                                                </div>
                                            </th>
                                            <th>
                                                <div class="input-group focused">
                                                    <input name="name" value="{{isset($params['name'])?$params['name']:''}}" class="form-control r-0" type="text" placeholder="Mahir">
                                                </div>
                                            </th>
                                            <th>
                                                <div class="input-group focused">
                                                    <input name="surname" value="{{isset($params['surname'])?$params['surname']:''}}" class="form-control r-0" type="text" placeholder="Abdullayev">
                                                </div>
                                            </th>
                                            <th>
                                                {{--<div class="input-group focused">
                                                    <select name="method" id="method" class="form-control">
                                                        <option value="">Hamısı</option>
                                                        @foreach($roles as $role)
                                                            <option {{isset($params['role']) && $params['role'] === $role->name ? 'selected' : ''}} value="{{$role->name}}">{{$role->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>--}}
                                            </th>
                                            <th></th>
                                        </form>
                                    </tr>
                                    </form>
                                    @foreach($data as $admin)
                                    <tr>
                                        <td style="font-weight: bold;">{{$admin->id}}</td>
                                        <td style="font-weight: bold;">{{$admin->name}}</td>
                                        <td style="font-weight: bold;">{{$admin->surname}}</td>
                                        <td style="font-weight: bold;">
                                            <?php $roleNames = ''; ?>
                                            @foreach($admin->relAdminRoles as $value)
                                                <?php $roleNames = $roleNames. ', '.$value->relRole->name; ?>
                                            @endforeach
                                            {{rtrim(ltrim($roleNames,", "))}}
                                        </td>
                                        <td>
                                            <a style="width: 40px; height: 38px;" href="{{url('az/admin/admins/'.$admin->id.'/edit')}}" class="btn btn-success btn-xs purple">
                                                <i style="font-size: 17px;padding-top: 5px;" class="far fa-edit"></i>
                                            </a>
                                            {{ Form::open(array('url' => App::getLocale()."/admin/admins/". $admin->id,'style' => 'display:inline')) }}
                                            {{ Form::hidden('_method', 'DELETE') }}
                                            {{ Form::macro('myField', function() { return '<button class="btn btn-danger" type="submit"><i class="far fa-trash-alt"></i></button>';})}}
                                            <?php echo Form::myField() ?>
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-md-12">
                                {{ $data->appends($params)->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $searchContainer = $('.search-container');
        $searchContainer.find('input').each(function() {
            $(this).on('keyup', function(e){
                if(e.keyCode === 13)
                {
                    console.log('key press');
                    $('#searchForm').submit();
                }
            });
        });

        $searchContainer.find('select').change(function () {
            $('#searchForm').submit();
        })
    </script>
@endsection