routes/admin.php
<?php
use App\Message;
// delete news file


Route::get('/login', 'Auth\LoginController@showAdminLoginForm')->name('admin.login.form');
Route::get('/admin-user', function() {
    return response()->json(Auth::guard('admin')->user(), 200);
});
Route::get('/register', 'Auth\RegisterController@showAdminRegisterForm')->name('admin.register');
Route::get('/logout', 'Auth\LoginController@adminLogout')->name('admin.logout');

Route::post('/login', 'Auth\LoginController@adminLogin')->name('admin.login');
Route::post('/register', 'Auth\RegisterController@createAdmin');

Route::group(['middleware' => 'auth:admin', 'namespace' => 'Admin'], function () {
    Route::post('/delete-news-file', 'NewsController@deleteFile');

    Route::get('/welcome-admin', 'WelcomeController@index');
    Route::resource('/news', 'NewsController');
    Route::get('/order/list', 'OrderController@index');
    Route::resource('/shops', 'ShopsController');
    Route::resource('/partners', 'PartnersController');
    Route::resource('/faq', 'FaqController');
    Route::resource('/countries', 'CountriesController');
    Route::resource('/roles', 'RolesController');
    Route::resource('/apis', 'ApisController');
    Route::resource('/admins', 'AdminsController');
    Route::resource('/slider', 'SliderController');
    Route::resource('/all-invoices', 'AllInvoicesController');
    Route::get('/contact', 'ContactController@index')->name('admin.contact.index');

    Route::resource('/invoices', 'InvoiceController');
    Route::get('/invoices/get/xml', 'InvoiceController@xml');
//    Route::get('/invoices/status', 'InvoiceController@getDataStatus');
    Route::get('/invoices/get/test', 'InvoiceController@test');
    Route::get('/invoices/get/test111', 'InvoiceController@test111');
    Route::get('/invoices/change-purchase/{purchase_no}', 'InvoiceController@changePurchase');
    Route::get('/invoices/get/manifest', 'InvoiceController@manifest');
    Route::get('/invoices/get/manifest2', 'InvoiceController@manifest2');
    Route::post('/invoices/check-storage', 'InvoiceController@addToOnTheWay');
    Route::post('/invoices/check-waiting', 'InvoiceController@addToForeignStorage');
    Route::post('/invoices/check-road', 'InvoiceController@addToStorage');
    Route::post('/invoices/check-native-storage', 'InvoiceController@addToCompleted');
    Route::post('/invoices/change-status', 'InvoiceController@changeStatus');
    Route::post('/invoices/change-all-stauses', 'InvoiceController@changeAllStatuses');
    Route::post('/invoices/send-invoiceless-message', 'InvoiceController@sendInvoicelessMessage');
    Route::get('/invoices/waybill/{id}', 'InvoiceController@waybill');
    Route::resource('/sack', 'SackController');
    Route::get('/sack/get/test', 'SackController@test');
    Route::post('/sack/addInvoice', 'SackController@addInvoice');
    Route::get('/sack/invoices/{id}', 'SackController@invoices');
    Route::resource('/dispatch', 'DispatchController');
    Route::post('/dispatch/addSack', 'DispatchController@addSack');

    Route::get('/invoiceless', 'InvoicelessController@index')->name('invoiceless.index');
    Route::post('/invoiceless', 'InvoicelessController@store')->name('invoiceless.store');
    Route::post('/invoiceless/send/{id}', 'InvoicelessController@send')->name('invoiceless.send');
    Route::get('/invoiceless/done/{id}', 'InvoicelessController@done')->name('invoiceless.done');

    Route::get('/get-admin-data', 'AdminsController@getAdminId')->name('getAdminData');
    Route::get('/accountants', 'AdminsController@getAccountants')->name('getAccountants');
    Route::post('/rejection', 'ProductsController@rejection')->name('rejection');
    Route::post('/refusal', 'RelUserProductsController@refusal')->name('refusal');
    Route::post('/changeExtrasLink', 'ProductsController@changeExtrasLink')->name('changeExtrasLink');  // new

    Route::post('/order/invoice-upload', 'ProductsController@invoiceUpload')->name('invoiceUpload');
    Route::post('/order/invoice-upload_new', 'ProductsController@invoiceUpload_new')->name('invoiceUpload_new');
    Route::post('/order/invoice-upload/change', 'ProductsController@updateInvoice')->name('invoiceChangeFile');
    Route::post('/order/finish', 'AdminsAcceptedProductsController@finishOrder')->name('finishOrder');
    Route::post('/order/ordered', 'RelUserProductsController@ordered')->name('ordered');
    Route::post('/order/send/invoiceData', 'InvoiceController@setInvoiceDataByBuyer')->name('sendInvoiceData');
    Route::post('/order/update/invoiceData', 'InvoiceController@updateInvoiceDataByBuyer')->name('updateInvoiceData');

    Route::get('/my-orders/list', 'RelUserProductsController@myOrders')->name('myOrders');
    Route::get('/orders/list', 'RelUserProductsController@orders')->name('orders');
    Route::get('/will-upload-invoices/list', 'RelUserProductsController@willUploadInvoices')->name('willUploadInvoices');
    Route::post('/calc-additional-price', 'RelUserProductsController@calcAddPrice')->name('calcAddPrice');


    Route::get('/orders/log', 'AdminsAcceptedProductsController@getFinishedOrdersLog')->name('ordersLog');
    Route::get('/orders', 'AdminsAcceptedProductsController@getOrders')->name('orders');
    Route::get('/orders/detail/{id}', 'AdminsAcceptedProductsController@getOrderDetail')->name('orderDetail');
    Route::get('/orders/detail/by-admin/{id}', 'AdminsAcceptedProductsController@getOrderDetailByAdmin')->name('orderDetail');
    Route::get('/orders/detail/by-user/{id}', 'AdminsAcceptedProductsController@getOrderDetailByUser')->name('orderDetailByUser'); // new
    Route::get('/will-upload-invoice/detail/by-admin/{id}', 'AdminsAcceptedProductsController@getWillUploadInvoiceDetailByAdmin')->name('willUploadInvoiceDetail');
    Route::get('/orders/detail/log/by-admin/{id}', 'AdminsAcceptedProductsController@getOrderLogDetailByAdmin')->name('orderLogDetail');
    Route::get('/accept', 'AdminsAcceptedProductsController@index')->name('accept');
    Route::post('/accept-order', 'AdminsAcceptedProductsController@acceptOrder')->name('acceptOrder');
    Route::post('/addBalance', 'UsersController@addBalance')->name('addBalance');
    Route::post('/accept/order/{id}', 'AdminsAcceptedProductsController@order')->name('order');

    Route::get('/courier', 'CourierController@index')->name('courier');

    Route::get('/courier/orders-answer-waiting', 'CourierController@getCourierAnswerOrders')->name('getCourierAnswerOrders');
    Route::get('/courier/orders-waiting', 'CourierController@getCourierOrders')->name('getCourierOrders');
    Route::get('/courier/reject-order', 'CourierController@rejectOrder');
    Route::get('/courier/check-depot', 'CourierController@checkDepot');
    Route::get('/courier/orders-delivered', 'CourierController@getDeliveredOrders')->name('getDeliveredOrders');
    Route::get('/courier/courier-users', 'CourierController@getCourierUsers')->name('getCourierUsers');
    Route::get('/courier/orders-delivered2', 'CourierController@courierDeliveryLogs')->name('courierDeliveryLogs');
    Route::post('/courier/selected', 'CourierController@courierSelected')->name('courierSelected');
    Route::post('/courier/complete-order', 'CourierController@completeOrder')->name('completeOrder');
    Route::post('/courier/give-to-depot', 'CourierController@giveToDepot')->name('giveToDepot');
    Route::get('/courier/orders-count', 'CourierController@ordersCount');
    Route::get('/courier/orders-complete-delivered/{id}', 'CourierController@completeDelivereOrder')->name('completeDeliveredOrder');
    Route::post('/courier/finish', 'CourierController@productDelivered')->name('productDelivered');
    Route::get('/courier/logs', 'CourierController@courierDeliveryLogs')->name('courierDeliveryLogs');
    Route::post('/courier/addCourier', 'CourierController@addCourier');
    Route::get('/courier/getCourierInvoices', 'CourierController@getCourierInvoices');

    Route::post('/problems/lost-packages', 'ProblemsController@searchLostPackages');
    Route::post('/problems/user-complains', 'ProblemsController@searchUserComplains');
    Route::get('/problems/complaint-types', 'ProblemsController@getComplaintTypes');
    Route::get('/problems/complaints', 'ProblemsController@getComplaints');
    Route::get('/problems/user-complaints', 'ProblemsController@getUserComplaints');
//    Route::post('/problems/add-complaint', 'ProblemsController@addComplaint');
    Route::get('/problems/get-complaint/{id}', 'ProblemsController@getComplaint');
    Route::post('/problems/send-message', 'ProblemsController@sendMessagetoUser');
//    Route::get('/problems/solve-complaint/{id}', 'ProblemsController@solveComplaint');
    Route::get('/problems/formal-complaints/{type}', 'ProblemsController@formalComplaints')->name('formalComplaints');

    Route::get('/user/list', 'UsersController@index')->name('users.list');
    Route::get('/user/allData/{id}', 'UsersController@allData')->name('users.allData');
    Route::get('/user/allData', 'UsersController@allData')->name('users.allData');
    Route::post('/user/sendEmail', 'UsersController@sendEmail')->name('users.sendEmail');
    Route::get('/user/sendEmailForAll', 'UsersController@sendEmailForAll')->name('users.sendEmail');
    Route::post('/user/sendSms', 'UsersController@sendSms')->name('users.sendSms');
    Route::get('/user/sendSmsForAll', 'UsersController@sendSmsForAll')->name('users.sendSms');

    Route::post('/product/comment', 'ProductsController@comment')->name('product.saveComment');
    Route::post('/product/saveRealPrice', 'ProductsController@saveRealPrice')->name('product.saveRealPrice');


    Route::get('/get-product-data-by-id/{id}', 'ProductsController@getProductDataById')->name('getProductDataById');
    Route::get('/print-hawb/{productId}', 'ProductsController@printHawb')->name('printHawb');
    Route::get('/user/list/block/{id}', 'UsersController@block')->name('users.block');

routes/web.php
<?php

Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/password/reset2', '\App\Http\Controllers\Site\FrontController@passwordResetWithPhone');

// CP Panel
Route::group(['middleware' => 'auth:admin', 'namespace' => 'Admin'], function (){
    Route::get('/cp', function () {
        return view('admin/welcomeadmin');
    });
});
// SIte papkasinin icindedirpayment-balance-success
Route::group(['namespace' => 'Site','as' => 'front.', 'middleware' => 'web'], function() {
    Route::get('/', 'FrontController@index')->name('main'); //OK
    Route::get('/countries', 'CountryController@index')->name('country'); //OK
    Route::get('/calculator', 'CalculatorController@index')->name('calculator'); //OK
    //Route::get('/premium', 'CalculatorController@premium')->name('premium'); //OK
    Route::post('/calculate', 'CalculatorController@calculate'); //OK
    Route::get('/calculate-currency', 'CalculatorController@calculateCurrency')->name('currency'); //Ok
    Route::get('/shops/country/{country}', 'ShopsController@index')->name('shop'); //OK
    Route::resource('/contact', 'ContactController'); //OK
    Route::get('/istifadeci-qaydalari', 'FrontController@userRules')->name('static.pages.userRules'); //OK
    Route::get('/suallar', 'FrontController@userQuestions')->name('static.pages.userQuestions'); //OK
    Route::get('/blog/{id}/{slug}', 'FrontController@newsIn'); //OK
    Route::get('/blog/{id}', 'FrontController@newsIn'); //OK

    Route::get('/news-and-announcements/{id}', 'FrontController@newsIn'); //lazimsiz
    Route::get('/news-and-announcements/{id}/{slug}', 'FrontController@newsIn'); //lazimsiz
    Route::get('/payment-balance-success', 'Panel\PaymentForBalanceController@getResponseOfPayment'); // Balansdan odenis
    Route::get('/success', 'FrontController@success')->name('success');
    Route::get('/password-sent', 'FrontController@passwordSent')->name('passwordSent2');
    Route::get('/anbar-tr', 'HomeController@anbar')->name('anbar');

    Route::post('/payment-callback', 'PaymentForProductController@getResponseOfPayment');// paytr    callbak post url
    Route::post('/payment-order-notify', 'OrderController@paymentNotify'); // paytr 2ci addim
    Route::get('/get-currency/{type}', 'FrontController@getCurrency');

    // payment callback
    Route::get('/payment-order-success', 'FrontController@paymentSuccess'); // Kart odenisi
    Route::get('/payment-success', 'FrontController@paymentSuccessBalance'); // Balans odenisi
    Route::get('/balancePayment', 'PaymentController@millionApi');
    Route::get('/{slug}', 'FrontController@staticPages')->name('static.pages.show');
});


Route::group(['namespace' => 'Front', 'middleware' => 'web'], function() {

});


//  Site papkasinin icindedir   /site/..
Route::group([ 'middleware' => ['web', 'auth'], 'namespace' => 'Site','prefix' => 'site','as' => 'front.'], function() { // authenticated routes
    Route::get('/invoice', 'InvoiceController@index')->name('invoice.index');
    Route::get('/productTypes', 'InvoiceController@productTypes')->name('invoice.product.types');
    Route::post('/invoice', 'InvoiceController@store')->name('invoice.store');
    Route::post('/invoice/edit', 'InvoiceController@edit')->name('invoice.edit');
/*
    Route::get('/track', 'Panel\TrackController@index');
    Route::get('/track/{type}', 'Panel\TrackController@index_new');
    Route::get('/track2/{type}', 'Panel\TrackController@index2');*/

});


// site papkasinin icinde ama site olmadan bir basa linkler
Route::group([ 'middleware' => ['web', 'auth'], 'namespace' => 'Site'], function() { // authenticated routes
    Route::post('/order/parse', 'OrderController@parse');
    Route::post('/order/link/insert', 'OrderController@store');
    Route::post('/order/link/insertBalance', 'OrderController@storeBalance');
});

// New User Panel Vue
Route::group([ 'middleware' => ['auth', 'isblocked'], 'namespace' => 'Site\Panel','prefix' => 'site'], function() { // authenticated routes
    Route::get('/user-panel', 'PanelController@index')->name('new-user-panel');
    Route::post('/user-panel', 'PanelController@index')->name('new-user-panel2');

    Route::get('/premium', 'PanelController@premium')->name('new-user-panel-premium');
    Route::post('/premium', 'PanelController@premium')->name('new-user-panel-premium');

    Route::get('/order/link/insert', 'OrderController@storeLink');


});

// New
/*Route::group([ 'middleware' => ['auth', 'isblocked'], 'namespace' => 'Site\Panel'], function() { // authenticated routes
    Route::get('/user-panel/get-user-data', 'PanelController@userData');
    Route::get('/user-panel/get-invoices/{type}', 'InvoicesController@index');
    Route::get('/user-panel/get-allInvoices-count', 'InvoicesController@allInvoicesCount');
    Route::get('/user-panel/get-invoices-count', 'InvoicesController@invoiceCount');
});*/

Route::group([ 'middleware' => ['auth', 'isblocked'], 'namespace' => 'Site\Panel'], function() { // authenticated routes
    Route::get('/panel/get-user-data', 'PanelController@userData');
    Route::get('/panel/clients', 'PanelController@getCorporateClients');
    Route::post('/panel/add-client', 'PanelController@addClient');
    Route::post('/panel/edit-client', 'PanelController@editClient');
    Route::get('/panel/get-invoices/{type}', 'InvoicesController@index');
    Route::get('/panel/get-invoice/{id}', 'InvoicesController@view');
    Route::get('/panel/get-invoices-count', 'InvoicesController@invoiceCount');
    Route::post('/panel/delete-invoice', 'InvoicesController@deleteInvoice');
    Route::get('/panel/order-status', 'InvoicesController@orderStatus');

});

//user-panel
Route::group([ 'middleware' => ['auth', 'isblocked'], 'namespace' => 'Front\Panel'], function() { // authenticated routes
    //Route::get('/user-panel', 'PanelController@index')->name('user-panel');
    Route::get('/user-panel/get-user-data', 'PanelController@userData');
    Route::get('/user-panel/get-user-data1', 'PanelController@userData1');
    Route::get('/user-panel/get-orders/{type}', 'OrderController@index');
    Route::get('/user-panel/get-orders2/{type}', 'OrderController@index2');
    Route::post('/user-panel/delete-basket/', 'OrderController@deleteBasket');
    Route::post('/user-panel/update-basket/', 'OrderController@updateBasket');
    Route::post('/user-panel/update-product/', 'OrderController@updateProduct');
    //Route::get('/user-panel/track', 'TrackController@index');
    Route::get('/user-panel/get-countries', 'InvoicesController@countries');
    Route::get('/user-panel/get-invoices/{type}', 'InvoicesController@index');
    Route::get('/user-panel/home_courier_invoices', 'InvoicesController@homeForCourier');
    Route::get('/user-panel/get-invoices2/{type}', 'InvoicesController@index2');
    Route::get('/user-panel/get-invoices-count', 'InvoicesController@invoiceCount');
    Route::get('/user-panel/get-allInvoices-count', 'InvoicesController@allInvoicesCount');
    Route::get('/user-panel/get-settings-data', 'SettingsController@index');
    Route::get('/user-panel/get-balance', 'BalanceController@index');
    Route::get('/user-panel/get-try-balance', 'BalanceController@indexTry');
    Route::post('/user-panel/post-settings-data', 'SettingsController@store');
    Route::post('/user-panel/post-settings-data-profile', 'SettingsController@storeProfile');
    Route::post('/user-panel/post-settings-data-passport', 'SettingsController@storePassport');
    Route::post('/user-panel/post-settings-data-password', 'SettingsController@storePassword');
    Route::post('/user-panel/post-courier-data', 'CourierController@store');
    Route::post('/user-panel/post-courier-data1', 'CourierController@store1');
    Route::post('/user-panel/post-transfer-data', 'CourierController@transferStore');
    Route::get('/user-panel/get-courier-data', 'CourierController@index');
    Route::get('/user-panel/get-courier-data2', 'CourierController@index2');
    Route::get('/user-panel/get-transfer-data', 'CourierController@indexTransfer');
    Route::get('/user-panel/get-complaints', 'QuestionsController@getComplaints');
    Route::get('/user-panel/get-complaints', 'QuestionsController@getComplaints');

    // Asistant
//    Route::post('/user-panel/get-questions', 'QuestionsdController@getDefaultQuestions');
//    Route::post('/user-panel/get-question', 'QuestionsdController@getDefaultQuestion');
//    Route::get('/user-panel/get-max-step', 'QuestionsdController@getMaxStepQuestions');

//    Route::post('/user-panel/get-questions', 'QuestionsddController@getDefaultQuestions');
//    Route::post('/user-panel/get-question', 'QuestionsddController@getDefaultQuestion');
//    Route::get('/user-panel/get-max-step', 'QuestionsddController@getMaxStepQuestions');

    Route::post('/user-panel/get-questions', 'QuestionsdddController@getDefaultQuestions');
    Route::post('/user-panel/get-question', 'QuestionsdddController@getDefaultQuestion');
    Route::get('/user-panel/get-max-step', 'QuestionsdddController@getMaxStepQuestions');
//    Route::post('/user-panel/get-next-step', 'QuestionsdddController@getNextStepQuestions');


//    Route::get('user-panel/get-complaints1', 'QuestionsController@getComplaints1');
    Route::get('/user-panel/get-complaint-messages/{id}', 'QuestionsController@getComplaintMessages');
    Route::post('/user-panel/add-complaint', 'QuestionsController@addComplaint');
    Route::get('/user-panel/complaint-types', 'QuestionsController@getComplaintTypes');
    Route::get('/user-panel/change-seen-status/{id}', 'QuestionsController@changeSeen');
    Route::post('/user-panel/send-message', 'QuestionsController@sendMessagetoAdmin');
    // for payment
    Route::post('/user-panel/pay', 'PanelController@pay');
    Route::post('/user-panel/pay-courier', 'PanelController@payOnlyCourier');
    Route::post('/user-panel/pay-courier1', 'PanelController@payOnlyCourier1');

resources/views/front/new/contact.blade.php
@extends('layouts.front_main')

@section('content')
    <section class="contact brands">
        @include('front.components.breadcrumb',['section' => 'contact'])
        <div class="contact-body">
            <div class="container">
                <div class="row relative">
                    <div class="col-xs-12">
                        <div class="contact-content invoice-left-side countries-body">
                            <div class="row">
                                @if (session('message'))
                                    <div class="alert alert-success">
                                        {{ session('message') }}
                                    </div>
                                @endif
                                <div class="col-sm-7 col-xs-12">
                                    <h1>@lang('common.contact')</h1>


                                    <ul class="nav nav-tabs country-inner-tabs" role="tablist">
                                        <li role="presentation" class="active">
                                            <a href="#baku" aria-controls="baku" role="tab" data-toggle="tab">
                                                @lang('panel-errors.baku')
                                            </a>
                                        </li>
                                        <li role="presentation">
                                            <a href="#sumgait" aria-controls="sumgait" role="tab" data-toggle="tab">
                                                @lang('panel-errors.sumgait')
                                            </a>
                                        </li>
                                        <li role="presentation">
                                            <a href="#ganja" aria-controls="ganja" role="tab" data-toggle="tab">
                                                @lang('panel-errors.ganja')
                                            </a>
                                        </li>
                                    </ul>
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane fade in active" id="baku">
                                            <address>
                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/phone-call.png') }}" alt="phone-call"> *9595
                                                </div>
                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/whatsapp2.png') }}" alt="phone-call"> 99450 824 95 95
                                                </div>

                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/envelope.png') }}" alt="envelope"> info@limak.az
                                                </div>
                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/place.png') }}" alt="place"> @lang('common.address')
                                                </div>
                                            </address>
                                        </div>
                                        <div role="tabpanel" class="tab-pane fade" id="sumgait">
                                            <address>
                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/phone-call.png') }}" alt="phone-call"> *9595
                                                </div>
                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/whatsapp2.png') }}" alt="phone-call"> 99450 824 95 95
                                                </div>

                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/envelope.png') }}" alt="envelope"> info@limak.az
                                                </div>
                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/place.png') }}" alt="place"> @lang('common.address-sumgait')
                                                </div>
                                            </address>
                                        </div>
                                        <div role="tabpanel" class="tab-pane fade" id="ganja">
                                            <address>
                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/phone-call.png') }}" alt="phone-call"> 994707279595
                                                </div>
                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/phone-call.png') }}" alt="phone-call"> *9595
                                                </div>
                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/whatsapp2.png') }}" alt="phone-call"> 99450 824 95 95
                                                </div>

                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/envelope.png') }}" alt="envelope"> info@limak.az
                                                </div>
                                                <div class="address">
                                                    <img src="{{ asset('front/new/img/place.png') }}" alt="place"> @lang('common.address-ganja')
                                                </div>
                                            </address>
                                        </div>
                                    </div>


                                </div>
                                <div class="col-sm-5 col-xs-12">
                                    <h3><b>@lang('common.write_us')</b></h3>
                                    <form action="{{ route('front.contact.store') }}" method="POST">
                                        <div class="row">
                                            <div class="col-xs-12">
                                                <div class="input-group border-radius">
                                                    <label>
                                                        <input type="text" name="name" class="form-control inputText" placeholder=" ">
                                                        <span>@lang('common.name_surname') * </span>
                                                    </label>
                                                </div>
                                                <div class="input-group border-radius">
                                                    <label>
                                                        <input type="text" name="email" class="form-control inputText" placeholder=" ">
                                                        <span>@lang('common.mail') * </span>
                                                    </label>
                                                </div>
                                                <div class="textarea-form form-group">
                                                    <textarea class="form-control" name="description"  rows="4" id="comment" placeholder="@lang('common.message') *"></textarea>
                                                </div>
                                                <button type="submit" class="btn-effect border-btn">@lang('common.send')</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div style="width: 100%">
            <iframe width="100%" height="600" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d319.53452916962686!2d49.8293159739942!3d40.365812947941436!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40307dc96ca1a6b1%3A0x3729c8228d2fdf4!2zMTEzIExlcm1vbnRvdiBTdHJlZXQsIEJha8SxLCDQkNC30LXRgNCx0LDQudC00LbQsNC9!5e0!3m2!1sru!2s!4v1550040327286" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
                <a href="https://www.maps.ie/map-my-route/">Create route map</a>
            </iframe>
        </div>
    </section>
@endsection

resources/views/front/new/success.blade.php
@extends('layouts.front_main')

@section('content')
    <section class="success invoice content">
        <div class="container">
            <div class="row">
                <div class="invoice-head col-xs-12">
                    <div class="col-md-4 col-sm-5 col-xs-7">
                        <h4>@lang('register.user_register')</h4>
                    </div>
                    <div class="col-md-8 col-sm-7 col-xs-6">
                        <ol class="breadcrumb web">
                            <li><a href="{{ route('front.main') }}">@lang('register.home_page') </a></li>
                            <li class="active"> @lang("register.register")</li>
                        </ol>
                        <ol class="breadcrumb mobile">
                            <li><a href="{{ route('front.main') }}">... </a></li>
                            <li class="active">@lang("register.register")</li>
                        </ol>
                    </div>
                </div>
                <div class="invoice-body col-xs-12">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="invoice-left-side block">
                                <div class="left-content text-center">
                                    <div class="row relative">
                                        <div class="success-left col-sm-6 col-xs-12">
                                            <h2>@lang("panel-errors.finished_register")</h2>

                                        </div>
                                        <div class=" success-right col-sm-6 col-xs-12">
                                            <div class="success-img">
                                                <img src="{{ asset('front/new/img/success.png') }}" alt="success" class="img-responsive center-block">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script>
        let route = '{{ route('new-user-panel') }}'
        setTimeout(function(){
            window.location.replace(route);
        }, 5000);
    </script>
@endsection